/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridge from "./bridge";
export type { bridge };
export type { AssetGovernance } from "./AssetGovernance";
export type { AssetNFT } from "./AssetNFT";
export type { FractionalShare } from "./FractionalShare";
export type { KYCRegistry } from "./KYCRegistry";
