/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  DoubleEndedQueueUpgradeable,
  DoubleEndedQueueUpgradeableInterface,
} from "../../../../../@openzeppelin/contracts-upgradeable/utils/structs/DoubleEndedQueueUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "Empty",
    type: "error",
  },
  {
    inputs: [],
    name: "OutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f8e06e63aa8229461bfada5f827cf8dd2d36b5d7013b138c59b4b1f99326e55d64736f6c63430008140033";

type DoubleEndedQueueUpgradeableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DoubleEndedQueueUpgradeableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DoubleEndedQueueUpgradeable__factory extends ContractFactory {
  constructor(...args: DoubleEndedQueueUpgradeableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DoubleEndedQueueUpgradeable & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): DoubleEndedQueueUpgradeable__factory {
    return super.connect(runner) as DoubleEndedQueueUpgradeable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DoubleEndedQueueUpgradeableInterface {
    return new Interface(_abi) as DoubleEndedQueueUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DoubleEndedQueueUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as DoubleEndedQueueUpgradeable;
  }
}
