/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetBridgeDestinationSol from "./AssetBridgeDestination.sol";
export type { assetBridgeDestinationSol };
export type { AssetBridgeSource } from "./AssetBridgeSource";
export type { WrappedAsset721 } from "./WrappedAsset721";
