/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWrappedAsset721,
  IWrappedAsset721Interface,
} from "../../../../contracts/bridge/AssetBridgeDestination.sol/IWrappedAsset721";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "exists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "mintTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWrappedAsset721__factory {
  static readonly abi = _abi;
  static createInterface(): IWrappedAsset721Interface {
    return new Interface(_abi) as IWrappedAsset721Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWrappedAsset721 {
    return new Contract(address, _abi, runner) as unknown as IWrappedAsset721;
  }
}
