/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetBridgeDestination } from "./AssetBridgeDestination";
export type { IWrappedAsset721 } from "./IWrappedAsset721";
